# This compose file is for demonstration only, do not use in prod.
version: "3.9"
services:
  couchbase:
    image: couchbase:community
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"
    volumes:
      - couchbase-data:/opt/couchbase

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - couchbase
    ports:
      - "4545:4545"
    env_file:
      - .env
    develop:
      watch:
        - path: .
          action: rebuild
          target: api
          ignore:
            - node_modules/**
        - path: .
          action: restart
          target: api
          ignore:
            - node_modules/**

volumes:
  couchbase-data: